"""
Naming Engine — the internal naming engine for the Structure Generation
Engine (Specification 006).

All file and folder names produced by the Structure Generation Engine
are generated by this small, stateless helper.  The naming engine
ensures that every name is:

* **Clear** — the name reflects the folder/file's purpose.
* **Professional** — names follow Python and industry conventions.
* **Consistent** — the same concept always gets the same name.
* **Language-compatible** — names are valid Python identifiers and
  valid filesystem names (no spaces, no special characters).
* **Best-practices compatible** — names follow PEP 8 for Python
  modules (``snake_case``) and standard conventions for config files
  (``lowercase.ext``).

The naming engine is deliberately stateless.  It exposes pure
functions that take a concept string and return a normalised name.  It
does **not** generate random names — it maps semantic concepts to
deterministic, professional names.
"""

from __future__ import annotations

import re
from typing import List


# ---------------------------------------------------------------------------#
# Reserved Python names that must never be used as module names
# ---------------------------------------------------------------------------#

_RESERVED_PYTHON_NAMES = frozenset({
    "import", "from", "class", "def", "return", "if", "else", "elif",
    "while", "for", "break", "continue", "pass", "lambda", "yield",
    "global", "nonlocal", "try", "except", "finally", "raise", "with",
    "as", "assert", "del", "in", "is", "not", "and", "or", "None",
    "True", "False", "bool", "int", "float", "str", "list", "dict",
    "set", "tuple", "type", "object", "id", "print", "input", "open",
    "file", "exec", "eval", "compile", "exit", "quit", "help", "dir",
    "main", "test", "tests", "setup", "config", "run", "utils",
})

# Common concept → standard name mappings.  These ensure consistency
# across all generated projects.
_STANDARD_NAMES = {
    "main": "main",
    "bot": "bot",
    "app": "app",
    "application": "app",
    "config": "config",
    "configuration": "config",
    "settings": "settings",
    "handlers": "handlers",
    "handler": "handlers",
    "models": "models",
    "model": "models",
    "database": "database",
    "db": "database",
    "services": "services",
    "service": "services",
    "middleware": "middleware",
    "utils": "utils",
    "utilities": "utils",
    "helpers": "helpers",
    "helper": "helpers",
    "core": "core",
    "tests": "tests",
    "test": "tests",
    "logs": "logs",
    "log": "logs",
    "assets": "assets",
    "resources": "resources",
    "locales": "locales",
    "i18n": "locales",
    "static": "static",
    "templates": "templates",
    "entrypoint": "main",
    "entry_point": "main",
    "cli": "cli",
    "api": "api",
    "admin": "admin",
    "auth": "auth",
    "authentication": "auth",
    "keyboards": "keyboards",
    "keyboard": "keyboards",
    "callbacks": "callbacks",
    "callback": "callbacks",
    "states": "states",
    "state": "states",
    "conversations": "conversations",
    "conversation": "conversations",
    "integrations": "integrations",
    "integration": "integrations",
    "migrations": "migrations",
    "migration": "migrations",
    "schemas": "schemas",
    "schema": "schemas",
    "repositories": "repositories",
    "repository": "repositories",
    "managers": "managers",
    "manager": "managers",
    "exceptions": "exceptions",
    "errors": "errors",
    "constants": "constants",
    "types": "types",
    "enums": "enums",
}


class NamingEngine:
    """Stateless helper that generates clear, professional, consistent names.

    The naming engine maps semantic concepts (strings like ``"handlers"``,
    ``"database connection"``, ``"user model"``) to deterministic,
    language-compatible names.  It is the **only** component that
    decides folder and file names in the structure generation engine.
    """

    # ------------------------------------------------------------------#
    # Core name generation
    # ------------------------------------------------------------------#

    @staticmethod
    def folder_name(concept: str) -> str:
        """Generate a professional folder name from a concept string.

        Examples::

            "handlers"        -> "handlers"
            "Database"        -> "database"
            "User Management" -> "user_management"
            "API Integration" -> "api_integration"
        """
        if not concept or not concept.strip():
            return "misc"
        key = concept.strip().lower().replace(" ", "_")
        if key in _STANDARD_NAMES:
            return _STANDARD_NAMES[key]
        return NamingEngine._slugify(concept)

    @staticmethod
    def file_name(concept: str, extension: str = "py") -> str:
        """Generate a professional file name from a concept string.

        Examples::

            "main"            -> "main.py"
            "Database Config" -> "database_config.py"
            "README"          -> "README.md"
        """
        if not concept or not concept.strip():
            name = "untitled"
        else:
            upper_concepts = {"readme", "license", "changelog", "makefile",
                              "dockerfile"}
            stripped = concept.strip()
            if stripped.lower() in upper_concepts:
                name = stripped.upper()
            else:
                name = NamingEngine._slugify(stripped)
        ext = extension.lstrip(".")
        if not ext:
            return name
        return f"{name}.{ext}"

    @staticmethod
    def python_module_name(concept: str) -> str:
        """Generate a Python module name (snake_case, no extension).

        Ensures the name is not a reserved Python keyword.
        """
        name = NamingEngine._slugify(concept)
        if name in _RESERVED_PYTHON_NAMES:
            name = f"{name}_module"
        return name

    @staticmethod
    def package_name(concept: str) -> str:
        """Generate a Python package name (snake_case).

        A package name must be a valid Python identifier and not a
        reserved keyword.  Standard concept mappings take precedence
        so that common names such as ``config`` and ``tests`` are
        preserved.
        """
        key = concept.strip().lower().replace(" ", "_")
        if key in _STANDARD_NAMES:
            return _STANDARD_NAMES[key]
        name = NamingEngine._slugify(concept)
        if name in _RESERVED_PYTHON_NAMES:
            name = f"{name}_pkg"
        if not name[0].isalpha() and name[0] != "_":
            name = f"pkg_{name}"
        return name

    @staticmethod
    def root_package_name(project_name: str) -> str:
        """Generate the root package name from the project name.

        Converts the project name to a valid Python package name.
        Examples::

            "My Store Bot"  -> "my_store_bot"
            "AI Assistant"  -> "ai_assistant"
        """
        if not project_name or not project_name.strip():
            return "telegram_bot"
        return NamingEngine._slugify(project_name)

    # ------------------------------------------------------------------#
    # Path helpers
    # ------------------------------------------------------------------#

    @staticmethod
    def join_path(*parts: str) -> str:
        """Join path parts with forward slashes (POSIX-style).

        Empty parts are dropped.  Leading/trailing slashes are removed.
        """
        cleaned: List[str] = []
        for part in parts:
            part = part.strip().strip("/")
            if part:
                cleaned.append(part)
        return "/".join(cleaned)

    @staticmethod
    def parent_path(path: str) -> str:
        """Return the parent path of a given path.

        Examples::

            "src/handlers/commands" -> "src/handlers"
            "main.py"                -> ""
            "src"                    -> ""
        """
        if not path:
            return ""
        parts = path.strip("/").split("/")
        if len(parts) <= 1:
            return ""
        return "/".join(parts[:-1])

    @staticmethod
    def base_name(path: str) -> str:
        """Return the last component of a path.

        Examples::

            "src/handlers/commands" -> "commands"
            "src/main.py"           -> "main.py"
            "main.py"               -> "main.py"
        """
        if not path:
            return ""
        return path.strip("/").split("/")[-1]

    # ------------------------------------------------------------------#
    # Internal
    # ------------------------------------------------------------------#

    @staticmethod
    def _slugify(text: str) -> str:
        """Convert arbitrary text to a snake_case slug.

        Rules:
        * Non-alphanumeric characters become underscores.
        * Multiple underscores collapse to one.
        * Leading/trailing underscores are stripped.
        * Result is lowercase.
        """
        if not text:
            return "unnamed"
        # Replace non-alphanumeric with underscores.
        slug = re.sub(r"[^a-zA-Z0-9]+", "_", text)
        # Collapse multiple underscores.
        slug = re.sub(r"_+", "_", slug)
        # Strip leading/trailing underscores.
        slug = slug.strip("_")
        # Lowercase.
        slug = slug.lower()
        # Ensure it starts with a letter or underscore.
        if slug and slug[0].isdigit():
            slug = f"_{slug}"
        return slug or "unnamed"


__all__ = ["NamingEngine"]
